# Generated by Django 2.2.7 on 2020-01-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_progress_sitting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitting',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='sitting',
            name='user',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Sitting',
        ),
    ]
