# Generated by Django 2.2.7 on 2020-03-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='q_type',
        ),
    ]
