# Generated by Django 2.2.7 on 2020-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200316_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='question time'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='q_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='question time'),
        ),
    ]
