# Generated by Django 2.2.7 on 2020-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200316_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='q_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='question time'),
        ),
    ]
